# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.field_guide_gui.animation.close_page_main.playing] run function aj:field_guide_gui/animations/close_page_main/zzz/on_tick
execute if entity @s[tag=aj.field_guide_gui.animation.close_page_spell_wheel.playing] run function aj:field_guide_gui/animations/close_page_spell_wheel/zzz/on_tick
execute if entity @s[tag=aj.field_guide_gui.animation.open_page_main.playing] run function aj:field_guide_gui/animations/open_page_main/zzz/on_tick
function aj:field_guide_gui/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~