# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(d_slot_8) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_8
$execute as $(d_slot_7) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_7
$execute as $(d_slot_6) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_6
$execute as $(d_slot_5) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_5
$execute as $(d_slot_4) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_4
$execute as $(d_slot_3) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_3
$execute as $(d_slot_2) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_2
$execute as $(d_slot_1) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_d_slot_1
$execute as $(spell_drawer_page_display) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_spell_drawer_page_display
$execute as $(spell_wheel_page_display) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_spell_wheel_page_display
$execute as $(w_slot_1) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_w_slot_1
$execute as $(w_slot_2) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_w_slot_2
$execute as $(w_slot_3) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_w_slot_3
$execute as $(w_slot_4) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_w_slot_4
$execute as $(spell_drawer_buttons) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_spell_drawer_buttons
$execute as $(spell_wheel_buttons) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_spell_wheel_buttons
$execute as $(exit) run function aj:fg_spell_wheel/variants/default/zzz/apply_to_node_exit