# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.open_page_main.frame
function aj:field_guide_gui/animations/open_page_main/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.open_page_main.frame matches 6.. run return run function aj:field_guide_gui/animations/open_page_main/pause
scoreboard players add @s aj.open_page_main.frame 1