# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.2018f,-0.6741f,0f,0.5966f,0.6741f,-0.2018f,0f,2.0992f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.2018f,-0.6741f,0f,-0.4334f,0.6741f,-0.2018f,0f,2.0893f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.2018f,-0.6741f,0f,0.0712f,0.6741f,-0.2018f,0f,0.4039f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.2018f,-0.6741f,0f,-0.5565f,0.6741f,-0.2018f,0f,0.3537f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.2018f,-0.6741f,0f,-0.9728f,0.6741f,-0.2018f,0f,1.7441f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.2018f,-0.6639f,0.1171f,-0.6593f,0.6741f,-0.1988f,0.035f,1.0805f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.2018f,-0.6639f,0.1171f,-0.6593f,0.6741f,-0.1988f,0.035f,1.0805f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.2018f,-0.6639f,0.1171f,-0.6593f,0.6741f,-0.1988f,0.035f,1.0805f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.2018f,-0.6741f,0f,0.6468f,0.6741f,-0.2018f,0f,1.4715f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.2018f,-0.6741f,0f,0.9077f,0.6741f,-0.2018f,0f,0.9069f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-0.2018f,-0.6741f,0f,-0.1537f,0.6741f,-0.2018f,0f,1.2318f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":0.4513,"py":2.1246,"pz":-0.5,"ry":360,"rx":0},"gear_interaction":{"px":-0.2016,"py":2.1586,"pz":-0.5,"ry":360,"rx":0},"collection_interaction":{"px":0.3029,"py":0.4733,"pz":-0.4687,"ry":360,"rx":0},"settings_interaction":{"px":-0.3374,"py":0.4652,"pz":-0.5,"ry":360,"rx":0},"spell_wheel_interaction":{"px":-0.7284,"py":1.7714,"pz":-0.5,"ry":360,"rx":0},"challenges_interaction":{"px":0.531,"py":1.4368,"pz":-0.5,"ry":360,"rx":0},"quests_interaction":{"px":0.8424,"py":0.8184,"pz":-0.5,"ry":360,"rx":0},"exit_interaction":{"px":-0.0273,"py":1.2697,"pz":-0.6875,"ry":360,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args