# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.2018f,-0.6741f,0f,0.9467f,-0.6741f,-0.2018f,0f,0.93f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.2018f,-0.6741f,0f,0.0807f,-0.6741f,-0.2018f,0f,0.3723f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.2018f,-0.6741f,0f,-0.4239f,-0.6741f,-0.2018f,0f,2.0577f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.2018f,-0.6741f,0f,-0.9759f,-0.6741f,-0.2018f,0f,1.7547f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.2018f,-0.6741f,0f,-0.5597f,-0.6741f,-0.2018f,0f,0.3643f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.2018f,-0.6639f,0.1171f,-0.6625f,-0.6741f,-0.1988f,0.035f,1.091f,0f,-0.1736f,-0.9848f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.2018f,-0.6639f,0.1171f,-0.6625f,-0.6741f,-0.1988f,0.035f,1.091f,0f,-0.1736f,-0.9848f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.2018f,-0.6639f,0.1171f,-0.6625f,-0.6741f,-0.1988f,0.035f,1.091f,0f,-0.1736f,-0.9848f,0.0609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [0.2018f,-0.6741f,0f,0.6437f,-0.6741f,-0.2018f,0f,1.482f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.2018f,-0.6741f,0f,0.5514f,-0.6741f,-0.2018f,0f,2.0971f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [0.2018f,-0.6741f,0f,-0.1569f,-0.6741f,-0.2018f,0f,1.2424f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":0.8392,"py":0.829,"pz":0,"ry":0,"rx":0},"gear_interaction":{"px":0.3124,"py":0.4417,"pz":0,"ry":0,"rx":0},"collection_interaction":{"px":-0.1922,"py":2.127,"pz":-0.0313,"ry":0,"rx":0},"settings_interaction":{"px":-0.7316,"py":1.7819,"pz":0,"ry":0,"rx":0},"spell_wheel_interaction":{"px":-0.3405,"py":0.4758,"pz":0,"ry":0,"rx":0},"challenges_interaction":{"px":0.5278,"py":1.4473,"pz":0,"ry":0,"rx":0},"quests_interaction":{"px":0.4482,"py":2.1351,"pz":0,"ry":0,"rx":0},"exit_interaction":{"px":-0.0305,"py":1.2802,"pz":0.1875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args