# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.5f,0f,0f,-0.4414f,0f,-0.5f,0f,1.8594f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.5f,0f,0f,-0.6445f,0f,-0.5f,0f,1.1563f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.5f,0f,0f,0.6055f,0f,-0.5f,0f,1.1563f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.5f,0f,0f,0.5117f,0f,-0.5f,0f,0.7187f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.5f,0f,0f,-0.5195f,0f,-0.5f,0f,0.7188f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.5f,0f,0f,-0.0039f,0f,-0.4924f,0.0868f,0.7969f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.5f,0f,0f,-0.0039f,0f,-0.4924f,0.0868f,0.7969f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.5f,0f,0f,-0.0039f,0f,-0.4924f,0.0868f,0.7969f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.5f,0f,0f,-0.0039f,0f,-0.5f,0f,1.7656f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.5f,0f,0f,0.4336f,0f,-0.5f,0f,1.8281f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-0.5f,0f,0f,-0.0039f,0f,-0.5f,0f,1.1719f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.4883,"py":1.7656,"pz":-0.5,"ry":0,"rx":0},"gear_interaction":{"px":-0.6445,"py":1.3281,"pz":-0.5,"ry":0,"rx":0},"collection_interaction":{"px":0.6055,"py":1.3281,"pz":-0.4687,"ry":0,"rx":0},"settings_interaction":{"px":0.4805,"py":0.8906,"pz":-0.5,"ry":0,"rx":0},"spell_wheel_interaction":{"px":-0.4883,"py":0.8906,"pz":-0.5,"ry":0,"rx":0},"challenges_interaction":{"px":-0.0039,"py":1.6797,"pz":-0.5,"ry":0,"rx":0},"quests_interaction":{"px":0.4805,"py":1.7656,"pz":-0.5,"ry":0,"rx":0},"exit_interaction":{"px":-0.0039,"py":1.2656,"pz":-0.6875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args