# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.085f,0.2838f,0f,-0.4097f,-0.2838f,-0.085f,0f,1.1334f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.085f,0.2838f,0f,-0.0451f,-0.2838f,-0.085f,0f,0.8985f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.085f,0.2838f,0f,0.1674f,-0.2838f,-0.085f,0f,1.6082f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.085f,0.2838f,0f,0.3998f,-0.2838f,-0.085f,0f,1.4806f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.085f,0.2838f,0f,0.2245f,-0.2838f,-0.085f,0f,0.8951f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.085f,0.2795f,-0.0493f,0.2678f,-0.2838f,-0.0837f,0.0148f,1.2011f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.085f,0.2795f,-0.0493f,0.2678f,-0.2838f,-0.0837f,0.0148f,1.2011f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.085f,0.2795f,-0.0493f,0.2678f,-0.2838f,-0.0837f,0.0148f,1.2011f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.085f,0.2838f,0f,-0.2821f,-0.2838f,-0.085f,0f,1.3658f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.085f,0.2838f,0f,-0.2433f,-0.2838f,-0.085f,0f,1.6248f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-0.085f,0.2838f,0f,0.0549f,-0.2838f,-0.085f,0f,1.2649f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.3645,"py":1.0908,"pz":-0.5,"ry":0,"rx":0},"gear_interaction":{"px":-0.1426,"py":0.9278,"pz":-0.5,"ry":0,"rx":0},"collection_interaction":{"px":0.0698,"py":1.6374,"pz":-0.4687,"ry":0,"rx":0},"settings_interaction":{"px":0.2969,"py":1.4921,"pz":-0.5,"ry":0,"rx":0},"spell_wheel_interaction":{"px":0.1323,"py":0.9421,"pz":-0.5,"ry":0,"rx":0},"challenges_interaction":{"px":-0.2333,"py":1.3512,"pz":-0.5,"ry":0,"rx":0},"quests_interaction":{"px":-0.1998,"py":1.6408,"pz":-0.5,"ry":0,"rx":0},"exit_interaction":{"px":0.0017,"py":1.2808,"pz":-0.6875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args