# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-1f,0f,0f,-0.875f,0f,1f,0f,0.125f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-1f,0f,0f,-1.2812f,0f,1f,0f,1.5313f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-1f,0f,0f,1.2188f,0f,1f,0f,1.5313f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-1f,0f,0f,1.0313f,0f,1f,0f,2.4063f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-1f,0f,0f,-1.0312f,0f,1f,0f,2.4063f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,2.25f,0f,-0.1736f,-0.9848f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,2.25f,0f,-0.1736f,-0.9848f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,2.25f,0f,-0.1736f,-0.9848f,0.0609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-1f,0f,0f,0.875f,0f,1f,0f,0.1875f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.9687,"py":0.3125,"pz":0,"ry":0,"rx":0},"gear_interaction":{"px":-1.2812,"py":1.1875,"pz":0,"ry":0,"rx":0},"collection_interaction":{"px":1.2188,"py":1.1875,"pz":-0.0312,"ry":0,"rx":0},"settings_interaction":{"px":0.9688,"py":2.0625,"pz":0,"ry":0,"rx":0},"spell_wheel_interaction":{"px":-0.9687,"py":2.0625,"pz":0,"ry":0,"rx":0},"challenges_interaction":{"px":0,"py":0.4844,"pz":0,"ry":0,"rx":0},"quests_interaction":{"px":0.9688,"py":0.3125,"pz":0,"ry":0,"rx":0},"exit_interaction":{"px":0,"py":1.3125,"pz":0.1875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args