# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.4898f,-0.6923f,0f,0.3054f,-0.6923f,0.4898f,0f,0.1771f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.4898f,-0.6923f,0f,-0.8671f,-0.6923f,0.4898f,0f,0.5847f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.4898f,-0.6923f,0f,0.3574f,-0.6923f,0.4898f,0f,2.3153f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.4898f,-0.6923f,0f,-0.3402f,-0.6923f,0.4898f,0f,2.6141f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.4898f,-0.6923f,0f,-1.3504f,-0.6923f,0.4898f,0f,1.1863f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.4898f,-0.6923f,0f,-0.391f,-0.6923f,0.4898f,0f,1.5787f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.4898f,-0.6923f,0f,-0.391f,-0.6923f,0.4898f,0f,1.5787f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.4898f,-0.6923f,0f,-0.391f,-0.6923f,0.4898f,0f,1.5787f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.4898f,-0.6923f,0f,0.6041f,-0.6923f,0.4898f,0f,0.8747f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.4898f,-0.6923f,0f,1.1192f,-0.6923f,0.4898f,0f,1.4192f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.4898f,-0.6923f,0f,-0.2179f,-0.6923f,0.4898f,0f,1.4563f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.1314,"py":1.3951,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args