# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.4898f,-0.6923f,0f,0.3679f,-0.6923f,0.4898f,0f,0.1146f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.4898f,-0.6923f,0f,-0.8046f,-0.6923f,0.4898f,0f,0.5222f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.4898f,-0.6923f,0f,0.4199f,-0.6923f,0.4898f,0f,2.2528f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.4898f,-0.6923f,0f,-0.2777f,-0.6923f,0.4898f,0f,2.5516f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.4898f,-0.6923f,0f,-1.2879f,-0.6923f,0.4898f,0f,1.1238f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.4898f,-0.6923f,0f,-0.3285f,-0.6923f,0.4898f,0f,1.5162f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.4898f,-0.6923f,0f,-0.3285f,-0.6923f,0.4898f,0f,1.5162f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.4898f,-0.6923f,0f,-0.3285f,-0.6923f,0.4898f,0f,1.5162f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.4898f,-0.6923f,0f,0.6666f,-0.6923f,0.4898f,0f,0.8122f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.4898f,-0.6923f,0f,1.1817f,-0.6923f,0.4898f,0f,1.3567f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.4898f,-0.6923f,0f,-0.1554f,-0.6923f,0.4898f,0f,1.3938f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":-0.0689,"py":1.3326,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args