# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.444f,-0.4385f,0f,0.8217f,-0.4385f,-0.444f,0f,1.4769f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.444f,-0.4385f,0f,0.3855f,-0.4385f,-0.444f,0f,0.6744f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.444f,-0.4385f,0f,-0.7245f,-0.4385f,-0.444f,0f,1.7705f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.444f,-0.4385f,0f,-1.0249f,-0.4385f,-0.444f,0f,1.2998f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.444f,-0.4385f,0f,-0.1092f,-0.4385f,-0.444f,0f,0.3955f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.444f,-0.4385f,0f,-0.2793f,-0.4385f,-0.444f,0f,1.1391f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.444f,-0.4385f,0f,-0.2793f,-0.4385f,-0.444f,0f,1.1391f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.444f,-0.4385f,0f,-0.2793f,-0.4385f,-0.444f,0f,1.1391f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [0.444f,-0.4385f,0f,0.351f,-0.4385f,-0.444f,0f,1.7773f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.444f,-0.4385f,0f,0.0173f,-0.4385f,-0.444f,0f,2.2164f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [0.444f,-0.4385f,0f,-0.1697f,-0.4385f,-0.444f,0f,1.2501f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.1149,"py":1.3056,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args