# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.444f,-0.4385f,0f,0.8842f,-0.4385f,-0.444f,0f,1.4144f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.444f,-0.4385f,0f,0.448f,-0.4385f,-0.444f,0f,0.6119f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.444f,-0.4385f,0f,-0.662f,-0.4385f,-0.444f,0f,1.708f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.444f,-0.4385f,0f,-0.9624f,-0.4385f,-0.444f,0f,1.2373f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.444f,-0.4385f,0f,-0.0467f,-0.4385f,-0.444f,0f,0.333f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.444f,-0.4385f,0f,-0.2168f,-0.4385f,-0.444f,0f,1.0766f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.444f,-0.4385f,0f,-0.2168f,-0.4385f,-0.444f,0f,1.0766f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.444f,-0.4385f,0f,-0.2168f,-0.4385f,-0.444f,0f,1.0766f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [0.444f,-0.4385f,0f,0.4135f,-0.4385f,-0.444f,0f,1.7148f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.444f,-0.4385f,0f,0.0798f,-0.4385f,-0.444f,0f,2.1539f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [0.444f,-0.4385f,0f,-0.1072f,-0.4385f,-0.444f,0f,1.1876f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":-0.0524,"py":1.2431,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args