# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.2675f,0.2642f,0f,-0.1438f,0.2642f,-0.2675f,0f,1.8822f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.2675f,0.2642f,0f,0.3364f,0.2642f,-0.2675f,0f,1.6133f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.2675f,0.2642f,0f,-0.3324f,0.2642f,-0.2675f,0f,0.9528f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.2675f,0.2642f,0f,-0.0511f,0.2642f,-0.2675f,0f,0.7683f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.2675f,0.2642f,0f,0.5007f,0.2642f,-0.2675f,0f,1.3132f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.2675f,0.2642f,0f,0.0514f,0.2642f,-0.2675f,0f,1.2163f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.2675f,0.2642f,0f,0.0514f,0.2642f,-0.2675f,0f,1.2163f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.2675f,0.2642f,0f,0.0514f,0.2642f,-0.2675f,0f,1.2163f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [0.2675f,0.2642f,0f,-0.3283f,0.2642f,-0.2675f,0f,1.6009f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.2675f,0.2642f,0f,-0.5955f,0.2642f,-0.2675f,0f,1.4031f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [0.2675f,0.2642f,0f,-0.0146f,0.2642f,-0.2675f,0f,1.2832f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.0476,"py":1.3166,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args