# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0878f,0.1241f,0f,-0.2899f,0.1241f,0.0878f,0f,1.3498f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0878f,0.1241f,0f,-0.1511f,0.1241f,0.0878f,0f,1.5237f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0878f,0.1241f,0f,0.0684f,0.1241f,0.0878f,0f,1.2135f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0878f,0.1241f,0f,0.1605f,0.1241f,0.0878f,0f,1.3136f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0878f,0.1241f,0f,-0.0206f,0.1241f,0.0878f,0f,1.5695f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0878f,0.1241f,0f,-0.0115f,0.1241f,0.0878f,0f,1.3839f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0878f,0.1241f,0f,-0.0115f,0.1241f,0.0878f,0f,1.3839f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0878f,0.1241f,0f,-0.0115f,0.1241f,0.0878f,0f,1.3839f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.0878f,0.1241f,0f,-0.1898f,0.1241f,0.0878f,0f,1.2577f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0878f,0.1241f,0f,-0.1285f,0.1241f,0.0878f,0f,1.1382f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0878f,0.1241f,0f,-0.0425f,0.1241f,0.0878f,0f,1.362f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.058,"py":1.351,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args