# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0878f,0.1241f,0f,-0.2274f,0.1241f,0.0878f,0f,1.2873f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0878f,0.1241f,0f,-0.0886f,0.1241f,0.0878f,0f,1.4612f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0878f,0.1241f,0f,0.1309f,0.1241f,0.0878f,0f,1.151f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0878f,0.1241f,0f,0.223f,0.1241f,0.0878f,0f,1.2511f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0878f,0.1241f,0f,0.0419f,0.1241f,0.0878f,0f,1.507f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0878f,0.1241f,0f,0.051f,0.1241f,0.0878f,0f,1.3214f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0878f,0.1241f,0f,0.051f,0.1241f,0.0878f,0f,1.3214f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0878f,0.1241f,0f,0.051f,0.1241f,0.0878f,0f,1.3214f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.0878f,0.1241f,0f,-0.1273f,0.1241f,0.0878f,0f,1.1952f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0878f,0.1241f,0f,-0.066f,0.1241f,0.0878f,0f,1.0757f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0878f,0.1241f,0f,0.02f,0.1241f,0.0878f,0f,1.2995f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":0.0045,"py":1.2885,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args