# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0876f,0.0826f,0f,-0.1792f,0.0826f,0.0876f,0f,1.2516f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0876f,0.0826f,0f,-0.0987f,0.0826f,0.0876f,0f,1.4083f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0876f,0.0826f,0f,0.1202f,0.0826f,0.0876f,0f,1.2018f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0876f,0.0826f,0f,0.1761f,0.0826f,0.0876f,0f,1.2939f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0876f,0.0826f,0f,-0.0045f,0.0826f,0.0876f,0f,1.4643f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0876f,0.0823f,-0.0072f,0.0729f,0.0826f,0.0872f,-0.0076f,1.3654f,0f,-0.0872f,-0.9962f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0876f,0.0823f,-0.0072f,0.0729f,0.0826f,0.0872f,-0.0076f,1.3654f,0f,-0.0872f,-0.9962f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0876f,0.0823f,-0.0072f,0.0729f,0.0826f,0.0872f,-0.0076f,1.3654f,0f,-0.0872f,-0.9962f,0.0609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.0876f,0.0826f,0f,-0.0872f,0.0826f,0.0876f,0f,1.1958f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0876f,0.0826f,0f,-0.0209f,0.0826f,0.0876f,0f,1.1126f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-0.0876f,0.0826f,0f,0.0109f,0.0826f,0.0876f,0f,1.2998f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.172,"py":1.2758,"pz":0,"ry":0,"rx":0},"gear_interaction":{"px":-0.1271,"py":1.3782,"pz":0,"ry":0,"rx":0},"collection_interaction":{"px":0.0918,"py":1.1717,"pz":-0.0313,"ry":0,"rx":0},"settings_interaction":{"px":0.1422,"py":1.269,"pz":0,"ry":0,"rx":0},"spell_wheel_interaction":{"px":-0.0274,"py":1.429,"pz":0,"ry":0,"rx":0},"challenges_interaction":{"px":-0.073,"py":1.2108,"pz":0,"ry":0,"rx":0},"quests_interaction":{"px":-0.0023,"py":1.1158,"pz":0,"ry":0,"rx":0},"exit_interaction":{"px":-0.0045,"py":1.2833,"pz":0.1875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args