# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.close_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args