# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.talents_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.gear_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.collection_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.settings_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.spell_wheel_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.challenges_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.quests_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.interactions.exit_interaction
function aj:field_guide_gui/zzz/at_all_interactions/execute_at_transform with storage animated_java:temp args