# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.fg_spell_wheel.animation.open.playing] run function aj:fg_spell_wheel/animations/open/zzz/on_tick
execute if entity @s[tag=aj.fg_spell_wheel.animation.close.playing] run function aj:fg_spell_wheel/animations/close/zzz/on_tick
function aj:fg_spell_wheel/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~