# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(d_slot_4) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_d_slot_4
$execute as $(w_slot_1) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_w_slot_1
$execute as $(w_slot_2) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_w_slot_2
$execute as $(w_slot_3) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_w_slot_3
$execute as $(w_slot_4) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_w_slot_4
$execute as $(exit) run function aj:fg_spell_wheel/variants/drawer_4_slot_4/zzz/apply_to_node_exit