# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(outer) {transformation: [0f,0.3135f,-0.63f,0.0625f,0f,-0.63f,-0.3135f,1.1875f,-1.5833f,0f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(middle) {transformation: [0f,0.4161f,0.2423f,0.0625f,0f,0.2423f,-0.4161f,1.1875f,-1.0833f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(logo) {transformation: [0f,0.2838f,-0.085f,0.0625f,0f,-0.085f,-0.2838f,1.1875f,-1f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.0617,"py":1.2247,"pz":-0.0625,"ry":360,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args