# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(outer) {transformation: [0f,-1.0595f,1.1766f,0.0625f,0f,-1.1766f,-1.0595f,1.1875f,1.5833f,0f,0f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(middle) {transformation: [0f,0.7249f,0.8051f,0.0625f,0f,-0.8051f,0.7249f,1.1875f,1.0833f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(logo) {transformation: [0f,0f,-1f,0.0625f,0f,1f,0f,1.1875f,1f,0f,0f,-0.1466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":0.0625,"py":-0.0625,"pz":0.6659,"ry":180,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args