# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:hpww_field_guide"
data modify storage animated_java:temp entry.data.rig_hash set value "382f2539c9fc799e7c61eef06608fcfe9d284d253c60907ef30629e94a54c172"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.talents] run function aj:hpww_field_guide/zzz/summon/as_node/talents
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.talents set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.spell_wheel] run function aj:hpww_field_guide/zzz/summon/as_node/spell_wheel
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.owl_post] run function aj:hpww_field_guide/zzz/summon/as_node/owl_post
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.owl_post set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.settings] run function aj:hpww_field_guide/zzz/summon/as_node/settings
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.settings set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.gear] run function aj:hpww_field_guide/zzz/summon/as_node/gear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.gear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.level] run function aj:hpww_field_guide/zzz/summon/as_node/level
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.level set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.challenges] run function aj:hpww_field_guide/zzz/summon/as_node/challenges
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.challenges set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_field_guide.node.qests] run function aj:hpww_field_guide/zzz/summon/as_node/qests
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.qests set from storage animated_java:gu out
function aj:hpww_field_guide/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:hpww_field_guide/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new