# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(w_slot_3) run function aj:fg_spell_wheel/variants/wheel_expelliarmus_slot_3/zzz/apply_to_node_w_slot_3
$execute as $(exit) run function aj:fg_spell_wheel/variants/wheel_expelliarmus_slot_3/zzz/apply_to_node_exit