# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.0876f,0.0826f,0f,-0.0274f,-0.0826f,0.0876f,0f,1.1084f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.0876f,0.0826f,0f,0.1243f,-0.0826f,0.0876f,0f,1.1979f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.0876f,0.0826f,0f,-0.0946f,-0.0826f,0.0876f,0f,1.4045f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.0876f,0.0826f,0f,-0.0059f,-0.0826f,0.0876f,0f,1.4656f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.0876f,0.0826f,0f,0.1747f,-0.0826f,0.0876f,0f,1.2952f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.0876f,0.0813f,-0.0143f,0.0715f,-0.0826f,0.0862f,-0.0152f,1.3667f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.0876f,0.0813f,-0.0143f,0.0715f,-0.0826f,0.0862f,-0.0152f,1.3667f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.0876f,0.0813f,-0.0143f,0.0715f,-0.0826f,0.0862f,-0.0152f,1.3667f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [0.0876f,0.0826f,0f,-0.0885f,-0.0826f,0.0876f,0f,1.1971f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.0876f,0.0826f,0f,-0.1755f,-0.0826f,0.0876f,0f,1.2584f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [0.0876f,0.0826f,0f,0.0096f,-0.0826f,0.0876f,0f,1.301f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.0037,"py":1.1171,"pz":-0.5,"ry":0,"rx":0},"gear_interaction":{"px":0.0959,"py":1.1679,"pz":-0.5,"ry":0,"rx":0},"collection_interaction":{"px":-0.1229,"py":1.3744,"pz":-0.4687,"ry":0,"rx":0},"settings_interaction":{"px":-0.0288,"py":1.4303,"pz":-0.5,"ry":0,"rx":0},"spell_wheel_interaction":{"px":0.1409,"py":1.2703,"pz":-0.5,"ry":0,"rx":0},"challenges_interaction":{"px":-0.0743,"py":1.2121,"pz":-0.5,"ry":0,"rx":0},"quests_interaction":{"px":-0.1733,"py":1.2771,"pz":-0.5,"ry":0,"rx":0},"exit_interaction":{"px":-0.0059,"py":1.2846,"pz":-0.6875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args