# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0805f,0.0578f,0f,-0.207f,0.0578f,0.0805f,0f,1.3008f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0805f,0.0578f,0f,-0.1584f,0.0578f,0.0805f,0f,1.4375f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0805f,0.0578f,0f,0.0429f,0.0578f,0.0805f,0f,1.293f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0805f,0.0578f,0f,0.0784f,0.0578f,0.0805f,0f,1.3742f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0805f,0.0578f,0f,-0.0877f,0.0578f,0.0805f,0f,1.4935f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0805f,0.0578f,0f,-0.0426f,0.0578f,0.0805f,0f,1.381f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0805f,0.0578f,0f,-0.0426f,0.0578f,0.0805f,0f,1.381f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0805f,0.0578f,0f,-0.0426f,0.0578f,0.0805f,0f,1.381f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.0805f,0.0578f,0f,-0.1257f,0.0578f,0.0805f,0f,1.2653f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0805f,0.0578f,0f,-0.0625f,0.0578f,0.0805f,0f,1.2046f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0805f,0.0578f,0f,-0.057f,0.0578f,0.0805f,0f,1.3609f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.0643,"py":1.3508,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args