# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0122f,0.2417f,0f,-0.2978f,0.2417f,0.0122f,0f,1.4767f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0122f,0.2417f,0f,0.0371f,0.2417f,0.0122f,0f,1.5921f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0122f,0.2417f,0f,0.0676f,0.2417f,0.0122f,0f,0.9879f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0122f,0.2417f,0f,0.2767f,0.2417f,0.0122f,0f,1.0438f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0122f,0.2417f,0f,0.2516f,0.2417f,0.0122f,0f,1.5423f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0122f,0.2417f,0f,0.1056f,0.2417f,0.0122f,0f,1.2851f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0122f,0.2417f,0f,0.1056f,0.2417f,0.0122f,0f,1.2851f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0122f,0.2417f,0f,0.1056f,0.2417f,0.0122f,0f,1.2851f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.0122f,0.2417f,0f,-0.2418f,0.2417f,0.0122f,0f,1.2676f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0122f,0.2417f,0f,-0.2614f,0.2417f,0.0122f,0f,1.0546f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0122f,0.2417f,0f,0.0451f,0.2417f,0.0122f,0f,1.282f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":0.0149,"py":1.2805,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args