# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.085f,0.2838f,0f,-0.2623f,0.2838f,-0.085f,0f,1.6257f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.085f,0.2838f,0f,0.1714f,0.2838f,-0.085f,0f,1.6215f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.085f,0.2838f,0f,-0.0411f,0.2838f,-0.085f,0f,0.9118f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.085f,0.2838f,0f,0.2232f,0.2838f,-0.085f,0f,0.8907f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.085f,0.2838f,0f,0.3985f,0.2838f,-0.085f,0f,1.4762f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.085f,0.2795f,-0.0493f,0.2665f,0.2838f,-0.0837f,0.0148f,1.1967f,0f,-0.1736f,-0.9848f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.085f,0.2795f,-0.0493f,0.2665f,0.2838f,-0.0837f,0.0148f,1.1967f,0f,-0.1736f,-0.9848f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.085f,0.2795f,-0.0493f,0.2665f,0.2838f,-0.0837f,0.0148f,1.1967f,0f,-0.1736f,-0.9848f,0.0609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [0.085f,0.2838f,0f,-0.2835f,0.2838f,-0.085f,0f,1.3614f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.085f,0.2838f,0f,-0.3933f,0.2838f,-0.085f,0f,1.1236f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [0.085f,0.2838f,0f,0.0536f,0.2838f,-0.085f,0f,1.2604f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.2011,"py":1.6363,"pz":0,"ry":0,"rx":0},"gear_interaction":{"px":0.0738,"py":1.6507,"pz":0,"ry":0,"rx":0},"collection_interaction":{"px":-0.1387,"py":0.9411,"pz":-0.0313,"ry":0,"rx":0},"settings_interaction":{"px":0.131,"py":0.9377,"pz":0,"ry":0,"rx":0},"spell_wheel_interaction":{"px":0.2956,"py":1.4876,"pz":0,"ry":0,"rx":0},"challenges_interaction":{"px":-0.2347,"py":1.3467,"pz":0,"ry":0,"rx":0},"quests_interaction":{"px":-0.3658,"py":1.0864,"pz":0,"ry":0,"rx":0},"exit_interaction":{"px":0.0004,"py":1.2764,"pz":0.1875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args