# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0122f,0.2417f,0f,-0.3603f,0.2417f,0.0122f,0f,1.5392f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0122f,0.2417f,0f,-0.0254f,0.2417f,0.0122f,0f,1.6546f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0122f,0.2417f,0f,0.0051f,0.2417f,0.0122f,0f,1.0504f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0122f,0.2417f,0f,0.2142f,0.2417f,0.0122f,0f,1.1063f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0122f,0.2417f,0f,0.1891f,0.2417f,0.0122f,0f,1.6048f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0122f,0.2417f,0f,0.0431f,0.2417f,0.0122f,0f,1.3476f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0122f,0.2417f,0f,0.0431f,0.2417f,0.0122f,0f,1.3476f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0122f,0.2417f,0f,0.0431f,0.2417f,0.0122f,0f,1.3476f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.0122f,0.2417f,0f,-0.3043f,0.2417f,0.0122f,0f,1.3301f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0122f,0.2417f,0f,-0.3239f,0.2417f,0.0122f,0f,1.1171f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0122f,0.2417f,0f,-0.0174f,0.2417f,0.0122f,0f,1.3445f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.0476,"py":1.343,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args