# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.3486f,0.2179f,0f,-0.02f,0.2179f,-0.3486f,0f,1.9358f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.3486f,0.2179f,0f,0.428f,0.2179f,-0.3486f,0f,1.5341f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.3486f,0.2179f,0f,-0.4434f,0.2179f,-0.3486f,0f,0.9893f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.3486f,0.2179f,0f,-0.1874f,0.2179f,-0.3486f,0f,0.7252f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.3486f,0.2179f,0f,0.5316f,0.2179f,-0.3486f,0f,1.1746f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.3486f,0.2179f,0f,0.0291f,0.2179f,-0.3486f,0f,1.1787f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.3486f,0.2179f,0f,0.0291f,0.2179f,-0.3486f,0f,1.1787f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.3486f,0.2179f,0f,0.0291f,0.2179f,-0.3486f,0f,1.1787f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [0.3486f,0.2179f,0f,-0.2841f,0.2179f,-0.3486f,0f,1.6797f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.3486f,0.2179f,0f,-0.6164f,0.2179f,-0.3486f,0f,1.5326f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [0.3486f,0.2179f,0f,-0.0254f,0.2179f,-0.3486f,0f,1.2658f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.0526,"py":1.3094,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args