# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.4994f,-0.3122f,0f,0.7237f,-0.3122f,-0.4994f,0f,1.6504f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.4994f,-0.3122f,0f,0.4876f,-0.3122f,-0.4994f,0f,0.8214f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.4994f,-0.3122f,0f,-0.7609f,-0.3122f,-0.4994f,0f,1.6018f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.4994f,-0.3122f,0f,-0.9404f,-0.3122f,-0.4994f,0f,1.1063f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.4994f,-0.3122f,0f,0.0896f,-0.3122f,-0.4994f,0f,0.4625f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.4994f,-0.3122f,0f,-0.2205f,-0.3122f,-0.4994f,0f,1.1121f,0f,0f,-1f,0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.4994f,-0.3122f,0f,-0.2205f,-0.3122f,-0.4994f,0f,1.1121f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.4994f,-0.3122f,0f,-0.2205f,-0.3122f,-0.4994f,0f,1.1121f,0f,0f,-1f,0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [0.4994f,-0.3122f,0f,0.2282f,-0.3122f,-0.4994f,0f,1.83f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.4994f,-0.3122f,0f,-0.1697f,-0.3122f,-0.4994f,0f,2.1655f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [0.4994f,-0.3122f,0f,-0.1425f,-0.3122f,-0.4994f,0f,1.237f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"interaction":{"px":-0.1035,"py":1.2994,"pz":1.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args