# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.0382f,-0.7571f,0f,0.8344f,-0.7571f,0.0382f,0f,0.5806f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.0382f,-0.7571f,0f,-0.2457f,-0.7571f,0.0382f,0f,0.3267f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.0382f,-0.7571f,0f,-0.1503f,-0.7571f,0.0382f,0f,2.2194f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.0382f,-0.7571f,0f,-0.8198f,-0.7571f,0.0382f,0f,2.1108f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.0382f,-0.7571f,0f,-0.8986f,-0.7571f,0.0382f,0f,0.5494f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.0382f,-0.7571f,0f,-0.3624f,-0.7571f,0.0382f,0f,1.3051f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.0382f,-0.7571f,0f,-0.3624f,-0.7571f,0.0382f,0f,1.3051f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.0382f,-0.7571f,0f,-0.3624f,-0.7571f,0.0382f,0f,1.3051f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.0382f,-0.7571f,0f,0.7259f,-0.7571f,0.0382f,0f,1.2502f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.0382f,-0.7571f,0f,0.8539f,-0.7571f,0.0382f,0f,1.9078f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.0382f,-0.7571f,0f,-0.1731f,-0.7571f,0.0382f,0f,1.2955f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":-0.0785,"py":1.2907,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args