# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.6398f,-0.6036f,0f,0.1353f,-0.6036f,0.6398f,0f,0.018f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.6398f,-0.6036f,0f,-0.9735f,-0.6036f,0.6398f,0f,0.6725f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.6398f,-0.6036f,0f,0.6261f,-0.6036f,0.6398f,0f,2.1816f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.6398f,-0.6036f,0f,-0.0221f,-0.6036f,0.6398f,0f,2.6283f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.6398f,-0.6036f,0f,-1.3417f,-0.6036f,0.6398f,0f,1.3833f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.6398f,-0.6013f,0.0526f,-0.5876f,-0.6036f,0.6374f,-0.0558f,1.9058f,0f,-0.0872f,-0.9962f,0.0641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.6398f,-0.6013f,0.0526f,-0.5876f,-0.6036f,0.6374f,-0.0558f,1.9058f,0f,-0.0872f,-0.9962f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.6398f,-0.6013f,0.0526f,-0.5876f,-0.6036f,0.6374f,-0.0558f,1.9058f,0f,-0.0872f,-0.9962f,0.0609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [-0.6398f,-0.6036f,0f,0.582f,-0.6036f,0.6398f,0f,0.6661f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.6398f,-0.6036f,0f,1.2173f,-0.6036f,0.6398f,0f,1.1143f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [-0.6398f,-0.6036f,0f,-0.1349f,-0.6036f,0.6398f,0f,1.4259f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":-0.0379,"py":0.0814,"pz":0,"ry":0,"rx":0},"gear_interaction":{"px":-0.766,"py":0.4526,"pz":0,"ry":0,"rx":0},"collection_interaction":{"px":0.8336,"py":1.9617,"pz":-0.0312,"ry":0,"rx":0},"settings_interaction":{"px":0.1454,"py":2.3706,"pz":0,"ry":0,"rx":0},"spell_wheel_interaction":{"px":-1.0942,"py":1.2011,"pz":0,"ry":0,"rx":0},"challenges_interaction":{"px":0.4782,"py":0.7761,"pz":0,"ry":0,"rx":0},"quests_interaction":{"px":1.2018,"py":1.2509,"pz":0,"ry":0,"rx":0},"exit_interaction":{"px":-0.0217,"py":1.306,"pz":0.1875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args