# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [0.6398f,-0.6036f,0f,1.245f,0.6036f,0.6398f,0f,1.0649f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [0.6398f,-0.6036f,0f,0.656f,0.6036f,0.6398f,0f,2.2099f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [0.6398f,-0.6036f,0f,-0.9435f,0.6036f,0.6398f,0f,0.7008f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [0.6398f,-0.6036f,0f,-1.3517f,0.6036f,0.6398f,0f,1.3738f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [0.6398f,-0.6036f,0f,-0.0321f,0.6036f,0.6398f,0f,2.6188f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [0.6398f,-0.5945f,0.1048f,-0.5976f,0.6036f,0.6301f,-0.1111f,1.8964f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [0.6398f,-0.5945f,0.1048f,-0.5976f,0.6036f,0.6301f,-0.1111f,1.8964f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [0.6398f,-0.5945f,0.1048f,-0.5976f,0.6036f,0.6301f,-0.1111f,1.8964f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [0.6398f,-0.6036f,0f,0.572f,0.6036f,0.6398f,0f,0.6567f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [0.6398f,-0.6036f,0f,0.0876f,0.6036f,0.6398f,0f,0.0485f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [0.6398f,-0.6036f,0f,-0.1449f,0.6036f,0.6398f,0f,1.4165f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":1.1918,"py":1.2415,"pz":-0.5,"ry":0,"rx":0},"gear_interaction":{"px":0.8635,"py":1.99,"pz":-0.5,"ry":0,"rx":0},"collection_interaction":{"px":-0.736,"py":0.4809,"pz":-0.4687,"ry":0,"rx":0},"settings_interaction":{"px":-1.1042,"py":1.1916,"pz":-0.5,"ry":0,"rx":0},"spell_wheel_interaction":{"px":0.1354,"py":2.3612,"pz":-0.5,"ry":0,"rx":0},"challenges_interaction":{"px":0.4682,"py":0.7667,"pz":-0.5,"ry":0,"rx":0},"quests_interaction":{"px":-0.0479,"py":0.0719,"pz":-0.5,"ry":0,"rx":0},"exit_interaction":{"px":-0.0317,"py":1.2965,"pz":-0.6875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args