# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [1f,0f,0f,0.8594f,0f,1f,0f,0.125f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [1f,0f,0f,1.2656f,0f,1f,0f,1.5313f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [1f,0f,0f,-1.2344f,0f,1f,0f,1.5313f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [1f,0f,0f,-1.0469f,0f,1f,0f,2.4063f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [1f,0f,0f,1.0156f,0f,1f,0f,2.4063f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(challenges) {transformation: [1f,0f,0f,-0.0156f,0f,1f,0f,0.3125f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [1f,0f,0f,-0.8906f,0f,1f,0f,0.1875f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(exit) {transformation: [1f,0f,0f,-0.0156f,0f,1f,0f,1.5f,0f,0f,1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"talents_interaction":{"px":0.9531,"py":0.3125,"pz":-0.5,"ry":0,"rx":0},"gear_interaction":{"px":1.2656,"py":1.1875,"pz":-0.5,"ry":0,"rx":0},"collection_interaction":{"px":-1.2344,"py":1.1875,"pz":-0.4687,"ry":0,"rx":0},"settings_interaction":{"px":-0.9844,"py":2.0625,"pz":-0.5,"ry":0,"rx":0},"spell_wheel_interaction":{"px":0.9531,"py":2.0625,"pz":-0.5,"ry":0,"rx":0},"challenges_interaction":{"px":-0.0156,"py":0.4844,"pz":-0.5,"ry":0,"rx":0},"quests_interaction":{"px":-0.9844,"py":0.3125,"pz":-0.5,"ry":0,"rx":0},"exit_interaction":{"px":-0.0156,"py":1.3125,"pz":-0.6875,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
$execute unless entity @s[tag=aj.transforms_only] as $(talents_interaction) positioned ^0.9531 ^0.3125 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_talents_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(gear_interaction) positioned ^1.2656 ^1.1875 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_gear_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(collection_interaction) positioned ^-1.2344 ^1.1875 ^-0.4687 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_collection_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(settings_interaction) positioned ^-0.9844 ^2.0625 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_settings_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(spell_wheel_interaction) positioned ^0.9531 ^2.0625 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_spell_wheel_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(challenges_interaction) positioned ^-0.0156 ^0.4844 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_challenges_interaction
$execute unless entity @s[tag=aj.transforms_only] as $(quests_interaction) positioned ^-0.9844 ^0.3125 ^-0.5 rotated ~0 ~0 run function aj:field_guide_gui/animations/open_page_main/zzz/frames/6_interaction_quests_interaction