# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) {transformation: [-0.7317f,-0.5255f,0f,-0.0347f,-0.5255f,0.7317f,0f,-0.0205f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(gear) {transformation: [-0.7317f,-0.5255f,0f,-1.071f,-0.5255f,0.7317f,0f,0.795f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(collection) {transformation: [-0.7317f,-0.5255f,0f,0.7583f,-0.5255f,0.7317f,0f,2.1087f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(settings) {transformation: [-0.7317f,-0.5255f,0f,0.1613f,-0.5255f,0.7317f,0f,2.6505f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(spell_wheel) {transformation: [-0.7317f,-0.5255f,0f,-1.3479f,-0.5255f,0.7317f,0f,1.5666f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(fill) {transformation: [-0.7317f,-0.5255f,0f,-0.2484f,-0.5255f,0.7317f,0f,1.6284f,0f,0f,-1f,-0.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(border) {transformation: [-0.7317f,-0.5255f,0f,-0.2484f,-0.5255f,0.7317f,0f,1.6284f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(number) {transformation: [-0.7317f,-0.5255f,0f,-0.2484f,-0.5255f,0.7317f,0f,1.6284f,0f,0f,-1f,-0.5016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(missions) {transformation: [-0.7317f,-0.5255f,0f,0.507f,-0.5255f,0.7317f,0f,0.5765f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(quests) {transformation: [-0.7317f,-0.5255f,0f,1.2129f,-0.5255f,0.7317f,0f,0.9449f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(close) {transformation: [-0.7317f,-0.5255f,0f,-0.1171f,-0.5255f,0.7317f,0f,1.4454f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"interactions":{"close_interaction":{"px":-0.0514,"py":1.354,"pz":0.3125,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args