# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:fg_spell_wheel"
data modify storage animated_java:temp entry.data.rig_hash set value "e879e8d689b7bdbeea3381aa63374d982428cfe6bcbc10a0ee076b800e1db2ff"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_8] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_7] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_6] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_5] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_4] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_3] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_2] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.d_slot_1] run function aj:fg_spell_wheel/zzz/summon/as_node/d_slot_1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.d_slot_1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.spell_drawer_page_display] run function aj:fg_spell_wheel/zzz/summon/as_node/spell_drawer_page_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_drawer_page_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.spell_wheel_page_display] run function aj:fg_spell_wheel/zzz/summon/as_node/spell_wheel_page_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel_page_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.w_slot_1] run function aj:fg_spell_wheel/zzz/summon/as_node/w_slot_1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w_slot_1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.w_slot_2] run function aj:fg_spell_wheel/zzz/summon/as_node/w_slot_2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w_slot_2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.w_slot_3] run function aj:fg_spell_wheel/zzz/summon/as_node/w_slot_3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w_slot_3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.w_slot_4] run function aj:fg_spell_wheel/zzz/summon/as_node/w_slot_4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w_slot_4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.spell_drawer_buttons] run function aj:fg_spell_wheel/zzz/summon/as_node/spell_drawer_buttons
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_drawer_buttons set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.spell_wheel_buttons] run function aj:fg_spell_wheel/zzz/summon/as_node/spell_wheel_buttons
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel_buttons set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fg_spell_wheel.node.exit] run function aj:fg_spell_wheel/zzz/summon/as_node/exit
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.exit set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:fg_spell_wheel/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:fg_spell_wheel/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new