# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(block_display) { transformation: [-0.875f,0f,0f,0.4375f,0f,1f,0f,-0.125f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display1) { transformation: [-0.9375f,0f,0f,0.4687f,0f,0.625f,0f,0.6875f,0f,0f,-0.9375f,0.4688f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(block_display3) { transformation: [-0.8125f,0f,0f,0.4062f,0f,0.6875f,0f,-0.1875f,0f,0f,-0.8125f,0.4063f,0f,0f,0f,1f], start_interpolation: -1 }