# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:hpww_alter"
data modify storage animated_java:temp entry.data.rig_hash set value "80857ec7c8fe7f1be152a9ba2962b974f0e2220f5a35d2486376484c54a0ebf8"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.hpww_alter.node.block_display] run function aj:hpww_alter/zzz/summon/as_node/block_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_alter.node.block_display1] run function aj:hpww_alter/zzz/summon/as_node/block_display1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_alter.node.block_display3] run function aj:hpww_alter/zzz/summon/as_node/block_display3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.block_display3 set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:hpww_alter/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:hpww_alter/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new