# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(fill) run function aj:field_guide_gui/variants/fill_19/zzz/apply_to_node_fill
$execute as $(close) run function aj:field_guide_gui/variants/fill_19/zzz/apply_to_node_close