# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_8_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_7_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_6_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_5_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_4_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_3_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_2_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.drawer_slot_1_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.curses_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.utility_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.force_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.control_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.damage_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.other_1_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.other_2_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.other_3_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.other_4_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.other_5_page_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_7_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_6_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_5_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_4_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_3_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_2_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_page_1_display_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_slot_1_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_slot_2_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_slot_3_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.wheel_slot_4_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.d_right_arrow_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.d_left_arrow_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.sp_left_arrow_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.sp_right_arrow_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.exit_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '4d5881b1205716527a05a8c66f5c3749cb4ea97938e0e569c35798d06935cc81'}}} run function animated_java:global/remove/outdated_rig
function aj:fg_spell_wheel/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack