# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(d_slot_8) { transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,0.6875f,0f,0f,-1f,-0.0469f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_7) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,0.6875f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_6) { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,0.6875f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_5) { transformation: [-1f,0f,0f,1f,0f,1f,0f,0.6875f,0f,0f,-1f,-0.0156f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_4) { transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,1.4375f,0f,0f,-1f,-0.0469f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_3) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.4375f,0f,0f,-1f,0.0625f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_2) { transformation: [-1f,0f,0f,1f,0f,1f,0f,1.4375f,0f,0f,-1f,-0.0156f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(d_slot_1) { transformation: [-1f,0f,0f,1f,0f,1f,0f,1.4375f,0f,0f,-1f,-0.0156f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(spell_drawer_page_display) { transformation: [-1.625f,0f,0f,0.0938f,0f,1.625f,0f,0.25f,0f,0f,-1.625f,-0.1062f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(spell_wheel_page_display) { transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,1.9612f,0f,0f,-1f,-0.0337f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(w_slot_1) { transformation: [-1f,0f,0f,1f,0f,1f,0f,2.5253f,0f,0f,-1f,-0.0215f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(w_slot_2) { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,2.5253f,0f,0f,-1f,0.041f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(w_slot_3) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,2.5253f,0f,0f,-1f,0.041f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(w_slot_4) { transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,2.5253f,0f,0f,-1f,-0.0527f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(spell_drawer_buttons) { transformation: [-2.2083f,0f,0f,-1.5f,0f,2.2083f,0f,1f,0f,0f,-2.2083f,-0.3281f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(spell_wheel_buttons) { transformation: [-2.2083f,0f,0f,1.625f,0f,2.2083f,0f,2.3125f,0f,0f,-2.2083f,-0.3906f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(exit) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }