# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) { transformation: [1f,0f,0f,0.8594f,0f,1f,0f,0.125f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(gear) { transformation: [1f,0f,0f,1.2656f,0f,1f,0f,1.5313f,0f,0f,1f,-0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(collection) { transformation: [1f,0f,0f,-1.2344f,0f,1f,0f,1.5313f,0f,0f,1f,-0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(settings) { transformation: [1f,0f,0f,-1.0469f,0f,1f,0f,2.4063f,0f,0f,1f,-0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(spell_wheel) { transformation: [1f,0f,0f,1.0156f,0f,1f,0f,2.4063f,0f,0f,1f,-0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(fill) { transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5641f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(border) { transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5625f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(number) { transformation: [1f,0f,0f,-0.0156f,0f,0.9848f,-0.1736f,2.25f,0f,0.1736f,0.9848f,-0.5609f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(challenges) { transformation: [1f,0f,0f,-0.0156f,0f,1f,0f,0.3125f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(quests) { transformation: [1f,0f,0f,-0.8906f,0f,1f,0f,0.1875f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(exit) { transformation: [1f,0f,0f,-0.0156f,0f,1f,0f,1.5f,0f,0f,1f,-0.5f,0f,0f,0f,1f], start_interpolation: 0 }