# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(talents) { transformation: [-1f,0f,0f,-0.9375f,0f,1f,0f,0.1875f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(gear) { transformation: [-1f,0f,0f,-1.3437f,0f,1f,0f,1.5938f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(collection) { transformation: [-1f,0f,0f,1.1563f,0f,1f,0f,1.5938f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(settings) { transformation: [-1f,0f,0f,0.9687f,0f,1f,0f,2.4688f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(spell_wheel) { transformation: [-1f,0f,0f,-1.0937f,0f,1f,0f,2.4688f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(fill) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,1.8125f,0f,0f,-1f,0.5016f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(border) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,1.8125f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(number) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,1.8125f,0f,0f,-1f,0.4984f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(missions) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,0.375f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(quests) { transformation: [-1f,0f,0f,0.8125f,0f,1f,0f,0.25f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(close) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,1.5625f,0f,0f,-1f,1f,0f,0f,0f,1f], start_interpolation: 0 }