# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(number) run function aj:field_guide_gui/variants/number_17/zzz/apply_to_node_number
$execute as $(exit) run function aj:field_guide_gui/variants/number_17/zzz/apply_to_node_exit