# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:field_guide_gui rig_hash set value '97f64e603f121f85b22c79af8081d335cef875a4f34ff9b8b68838d21614e8d1'
scoreboard objectives add aj.close_page_main.frame dummy
scoreboard objectives add aj.open_page_main.frame dummy