# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:field_guide_gui rig_hash set value '9791a4c57b94e70af665a3c7c6eff11588f5facbf6cff8a661f364676682ce44'
scoreboard objectives add aj.close_page_main.frame dummy
scoreboard objectives add aj.close_page_spell_wheel.frame dummy
scoreboard objectives add aj.open_page_main.frame dummy