# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:field_guide_gui rig_hash set value '0545f1216e4999ffae84136b2273d2bde0a0a0c4c8a52f80a6d5babee665ecc3'
scoreboard objectives add aj.close_page_main.frame dummy
scoreboard objectives add aj.open_page_main.frame dummy