# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(border) run function aj:field_guide_gui/variants/level_highlight/zzz/apply_to_node_border
$execute as $(exit) run function aj:field_guide_gui/variants/level_highlight/zzz/apply_to_node_exit