# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_8_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_7_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_6_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_5_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_4_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_3_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_2_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.drawer_slot_1_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.curses_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.utility_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.force_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.control_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.damage_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.other_1_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.other_2_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.other_3_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.other_4_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.other_5_page_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_7_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_6_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_5_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_4_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_3_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_2_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_page_1_display_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_slot_1_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_slot_2_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_slot_3_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.wheel_slot_4_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.d_right_arrow_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.d_left_arrow_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.sp_left_arrow_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.sp_right_arrow_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.close_interaction.uuid
function aj:fg_spell_wheel/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args