# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function aj:field_guide_gui/zzz/summon/zzz/1 $(talents_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/2 $(gear_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/3 $(collection_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/4 $(settings_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/5 $(spell_wheel_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/6 $(challenges_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/7 $(quests_interaction)
$function aj:field_guide_gui/zzz/summon/zzz/8 $(exit_interaction)