# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '2195219410e8c1b1f8a8ceda47cb2006fd8bffd41bcf4acc6f1461237c59c62e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack