# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'fcdc41d0409833447687839582ac9d1fd6a001cb423d3306244fac2956b9d714'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack