# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '13432d91556c85b108a5d813a9f0b5331a615c90c3ae0ca4c93e32d337360d93'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack