# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.protego.root] run return 0
execute if entity @s[tag=aj.protego.animation.protego_activate.playing] run function animated_java:protego/animations/protego_activate/zzz/on_tick
execute on passengers run rotate @s ~ ~