# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(talents) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_talents
$execute as $(gear) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_gear
$execute as $(collection) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_collection
$execute as $(settings) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_settings
$execute as $(spell_wheel) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_spell_wheel
$execute as $(fill) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_fill
$execute as $(border) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_border
$execute as $(number) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_number
$execute as $(challenges) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_challenges
$execute as $(quests) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_quests
$execute as $(exit) run function aj:field_guide_gui/variants/default/zzz/apply_to_node_exit