# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:protego/animations/pause_all
tag @s add aj.protego.animation.protego_deactivate.playing
scoreboard players set @s aj.protego_deactivate.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:protego/animations/protego_deactivate/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only