# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.close_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args