# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.talents_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.gear_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.collection_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.settings_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.spell_wheel_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.challenges_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.quests_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.interactions.exit_interaction.uuid
function aj:field_guide_gui/zzz/as_all_interactions/execute_as_uuid with storage animated_java:temp args