# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.talents_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.gear_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.collection_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.settings_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.spell_wheel_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.challenges_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.quests_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.exit_interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '8e32f6364c5930ad386251ac01eee4d9eeb141f9c38cbd2da603b2ca0e900c29'}}} run function animated_java:global/remove/outdated_rig
function aj:field_guide_gui/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack