# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(outer) { transformation: [0f,0f,1.5833f,0.0625f,0f,1.5833f,0f,1.1875f,-1.5833f,0f,0f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(middle) { transformation: [0f,0f,1.0833f,0.0625f,0f,1.0833f,0f,1.1875f,-1.0833f,0f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(logo) { transformation: [0f,0f,1f,0.0625f,0f,1f,0f,1.1875f,-1f,0f,0f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }