# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:hpww_trial_start_button/zzz/reset_floating_entities
function aj:hpww_trial_start_button/zzz/apply_default_pose_to_nodes with storage animated_java:temp entry.data.uuids_by_name