# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Keep execution positioned at this interaction so the player-side guard can read its spell ID.
execute positioned as @s on target run function hpww:main/field_guide/gui/spell_wheel_page/bind/select_drawer_spell {slot:1}
