# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on attacker run function hpww:main/field_guide/gui/spell_wheel_page/bind/bind_blank {slot:4}
