# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
data modify entity @s CustomName set value ['',{text:aj.fg_spell_wheel,color:'#00aced'},'.',{text:interaction,color:light_purple},'.',{text:wheel_slot_1_interaction,color:gold}]
function animated_java:global/gu/get_entity_uuid_string
scoreboard players operation @s aj.id = aj.last_id aj.id
data modify entity @s data.animated_java.on_interact_function set value "function aj:fg_spell_wheel/interactions/wheel_slot_1_interaction_on_interact"
data modify entity @s data.animated_java.on_attack_function set value "function aj:fg_spell_wheel/interactions/wheel_slot_1_interaction_on_attack"