# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from storage animated_java:temp entry.data.uuids_by_name.interaction
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '5b32c9ede4d88da7ce615fd1c0c13580da59417cb99bad6520889a080f2768ab'}}} run function animated_java:global/remove/outdated_rig
function aj:hpww_trial_start_button/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack