# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:hpww_trial_start_button rig_hash set value 'd9e9f0fc452732313278ed8330a8989025b58b36fff9ffa7f68b26ac1fa6fb1a'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.activate.frame dummy