# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:hpww_trial_start_button rig_hash set value '5b32c9ede4d88da7ce615fd1c0c13580da59417cb99bad6520889a080f2768ab'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.activate.frame dummy