# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:hpww_trial_start_button rig_hash set value '875b0e656241c76e370f6e10b546077781b30ba912b7d93c265ec2ba4d8ebd46'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.activate.frame dummy