# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.protego.animation.protego_active.playing] run function aj:protego/animations/protego_active/zzz/on_tick
execute if entity @s[tag=aj.protego.animation.protego_deactivate.playing] run function aj:protego/animations/protego_deactivate/zzz/on_tick
execute if entity @s[tag=aj.protego.animation.protego_block.playing] run function aj:protego/animations/protego_block/zzz/on_tick
execute on passengers run rotate @s ~ ~