# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone77] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone77 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone78] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone78 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone79] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone79 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone80] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone80 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone81] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone81 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone82] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone82 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone83] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone83 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone84] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone84 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone85] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone85 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone86] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone86 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone87] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone87 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone88] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone88 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone89] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone89 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone90] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone90 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone91] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone91 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone92] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone92 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone93] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone93 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone94] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone94 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone95] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone95 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone96] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone96 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone97] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone97 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone98] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone98 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone45] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone45 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone46] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone46 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone47] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone47 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone48] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone48 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone49] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone49 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone50] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone50 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone51] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone51 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone52] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone52 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone53] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone53 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone54] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone54 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone55] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone55 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone56] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone56 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone57] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone57 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone58] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone58 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone59] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone59 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone60] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone60 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone61] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone61 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone62] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone62 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone63] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone63 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone64] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone64 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone65] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone65 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone66] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone66 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone99] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone99 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone100] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone100 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone101] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone101 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone102] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone102 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone103] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone103 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone104] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone104 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone105] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone105 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone106] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone106 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone107] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone107 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone108] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone108 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone109] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone109 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone110] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone110 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone111] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone111 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone112] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone112 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone113] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone113 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone114] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone114 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone115] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone115 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone116] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone116 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone117] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone117 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone118] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone118 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone119] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone119 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone120] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone120 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone29] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone29 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone30] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone30 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone31] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone31 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone32] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone32 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone33] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone33 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone34] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone34 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone35] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone35 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone36] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone36 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone37] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone37 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone38] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone38 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone39] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone39 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone40] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone40 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone41] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone41 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone42] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone42 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone43] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone43 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone44] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone44 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone67] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone67 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone68] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone68 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone69] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone69 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone70] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone70 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone71] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone71 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone72] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone72 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone7 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone11] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone11 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone13] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone13 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone14] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone14 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone15] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone15 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone16] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone16 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone17] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone17 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone18] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone18 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone19] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone19 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone20] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone20 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone21] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone21 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone22] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone22 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone23] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone23 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone24] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone24 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone25] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone25 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone26] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone26 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone27] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone27 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone28] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone28 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone73] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone73 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone74] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone74 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone75] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone75 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone76] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone76 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone121] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone121 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone122] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone122 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone123] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone123 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone124] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone124 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone125] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone125 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone126] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone126 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone127] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone127 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone128] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone128 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone129] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone129 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone130] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone130 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone131] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone131 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone132] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone132 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.protego.node.bone133] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone133 set from storage animated_java:gu out