# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:hpww_trial_start_button"
data modify storage animated_java:temp entry.data.rig_hash set value "d9e9f0fc452732313278ed8330a8989025b58b36fff9ffa7f68b26ac1fa6fb1a"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0.0625 ^0 ^-0.6875 { Tags:["","aj.global.bone.bone.decendant","aj.global.bone.bone.decendant.interaction","aj.global.bone.bone.tree","aj.global.bone.logo.child","aj.global.bone.logo.child.interaction","aj.global.bone.logo.decendant","aj.global.bone.logo.decendant.interaction","aj.global.bone.logo.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.interaction","aj.hpww_trial_start_button.bone.bone.decendant","aj.hpww_trial_start_button.bone.bone.decendant.interaction","aj.hpww_trial_start_button.bone.bone.tree","aj.hpww_trial_start_button.bone.logo.child","aj.hpww_trial_start_button.bone.logo.child.interaction","aj.hpww_trial_start_button.bone.logo.decendant","aj.hpww_trial_start_button.bone.logo.decendant.interaction","aj.hpww_trial_start_button.bone.logo.tree","aj.hpww_trial_start_button.entity","aj.hpww_trial_start_button.interaction","aj.hpww_trial_start_button.interaction.interaction","aj.hpww_trial_start_button.node","aj.hpww_trial_start_button.node.interaction","aj.new"], response: false, width: 2.3125f, height: 2.375f, }
execute as @n[ type=minecraft:interaction, tag=aj.hpww_trial_start_button.interaction.interaction, tag=aj.new, distance=..3 ] run function aj:hpww_trial_start_button/zzz/summon/as_interaction/interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.interaction.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_trial_start_button.node.outer] run function aj:hpww_trial_start_button/zzz/summon/as_node/outer
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.outer set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_trial_start_button.node.middle] run function aj:hpww_trial_start_button/zzz/summon/as_node/middle
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.middle set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.hpww_trial_start_button.node.logo] run function aj:hpww_trial_start_button/zzz/summon/as_node/logo
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.logo set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:hpww_trial_start_button/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:hpww_trial_start_button/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:hpww_trial_start_button/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:hpww_trial_start_button/zzz/summon/zzz/0 with storage animated_java:temp entry.data.interactions
tag @s remove aj.new
execute on passengers run tag @s remove aj.new