# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:protego rig_hash set value '80a70eab61e4a5fc72fe9b13585d9a6b27d7293fedd9b9ad53edf4c72b0eac15'
scoreboard objectives add aj.protego_active.frame dummy
scoreboard objectives add aj.protego_deactivate.frame dummy
scoreboard objectives add aj.protego_block.frame dummy