# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.protego_deactivate.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:protego/animations/protego_deactivate/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove aj.protego.animation.protego_deactivate.playing