# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.hpww_trial_start_button.animation.idle.playing] run function aj:hpww_trial_start_button/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.hpww_trial_start_button.animation.activate.playing] run function aj:hpww_trial_start_button/animations/activate/zzz/on_tick
function aj:hpww_trial_start_button/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~