# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(talents)
$kill $(spell_wheel)
$kill $(owl_post)
$kill $(settings)
$kill $(gear)
$kill $(level)
$kill $(challenges)
$kill $(qests)