# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.hpww_trial_start_button.animation.idle.playing
tag @s remove aj.hpww_trial_start_button.animation.activate.playing