# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:protego rig_hash set value '13432d91556c85b108a5d813a9f0b5331a615c90c3ae0ca4c93e32d337360d93'
scoreboard objectives add aj.protego_activate.frame dummy