# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:protego rig_hash set value '2195219410e8c1b1f8a8ceda47cb2006fd8bffd41bcf4acc6f1461237c59c62e'
scoreboard objectives add aj.protego_active.frame dummy
scoreboard objectives add aj.protego_deactivate.frame dummy
scoreboard objectives add aj.protego_block.frame dummy