# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:protego rig_hash set value 'fcdc41d0409833447687839582ac9d1fd6a001cb423d3306244fac2956b9d714'
scoreboard objectives add aj.protego_active.frame dummy
scoreboard objectives add aj.protego_deactivate.frame dummy
scoreboard objectives add aj.protego_block.frame dummy