# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.protego.animation.protego_active.playing
tag @s remove aj.protego.animation.protego_deactivate.playing
tag @s remove aj.protego.animation.protego_block.playing