# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:fg_spell_wheel rig_hash set value '2101bda827fe339104b05bf27595e3011071aaa1d0f055c44e3b46427739f6db'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy