# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:fg_spell_wheel rig_hash set value '7d955283b99598e6b8a54161d5023bf52a1a238ee45add02b2da43fde0f327dc'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy