# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:fg_spell_wheel rig_hash set value '4d5881b1205716527a05a8c66f5c3749cb4ea97938e0e569c35798d06935cc81'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy