# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:field_guide_gui"
data modify storage animated_java:temp entry.data.rig_hash set value "c751b021dfca536f95588a147cc28a285784fbb3ffc2ad5ff70860084abba231"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.field_guide_gui.node.talents] run function aj:field_guide_gui/zzz/summon/as_node/talents
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.talents set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.gear] run function aj:field_guide_gui/zzz/summon/as_node/gear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.gear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.collection] run function aj:field_guide_gui/zzz/summon/as_node/collection
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.collection set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.settings] run function aj:field_guide_gui/zzz/summon/as_node/settings
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.settings set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.spell_wheel] run function aj:field_guide_gui/zzz/summon/as_node/spell_wheel
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.fill] run function aj:field_guide_gui/zzz/summon/as_node/fill
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.fill set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.border] run function aj:field_guide_gui/zzz/summon/as_node/border
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.border set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.number] run function aj:field_guide_gui/zzz/summon/as_node/number
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.number set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.missions] run function aj:field_guide_gui/zzz/summon/as_node/missions
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.missions set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.quests] run function aj:field_guide_gui/zzz/summon/as_node/quests
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.quests set from storage animated_java:gu out
function aj:field_guide_gui/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:field_guide_gui/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new