# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:field_guide_gui"
data modify storage animated_java:temp entry.data.rig_hash set value "1ee8df55c9a94bd919e0e7a30d5b8ad3145f7e78e463ae418d23b1f5bb5fe06c"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0.9531 ^0.3125 ^-0.5 { Tags:["","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.bone.talents.child","aj.field_guide_gui.bone.talents.child.interaction","aj.field_guide_gui.bone.talents.decendant","aj.field_guide_gui.bone.talents.decendant.interaction","aj.field_guide_gui.bone.talents.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.talents_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.talents_interaction","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.bone.talents.child","aj.global.bone.talents.child.interaction","aj.global.bone.talents.decendant","aj.global.bone.talents.decendant.interaction","aj.global.bone.talents.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.talents_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.talents_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/talents_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.talents_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.talents_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^1.2656 ^1.1875 ^-0.5 { Tags:["","aj.field_guide_gui.bone.gear.child","aj.field_guide_gui.bone.gear.child.interaction","aj.field_guide_gui.bone.gear.decendant","aj.field_guide_gui.bone.gear.decendant.interaction","aj.field_guide_gui.bone.gear.tree","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.gear_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.gear_interaction","aj.global.bone.gear.child","aj.global.bone.gear.child.interaction","aj.global.bone.gear.decendant","aj.global.bone.gear.decendant.interaction","aj.global.bone.gear.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.gear_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.gear_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/gear_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.gear_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.gear_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-1.2344 ^1.1875 ^-0.4687 { Tags:["","aj.field_guide_gui.bone.collection.child","aj.field_guide_gui.bone.collection.child.interaction","aj.field_guide_gui.bone.collection.decendant","aj.field_guide_gui.bone.collection.decendant.interaction","aj.field_guide_gui.bone.collection.tree","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.collection_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.collection_interaction","aj.global.bone.collection.child","aj.global.bone.collection.child.interaction","aj.global.bone.collection.decendant","aj.global.bone.collection.decendant.interaction","aj.global.bone.collection.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.collection_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.collection_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/collection_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.collection_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.collection_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-0.9844 ^2.0625 ^-0.5 { Tags:["","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.bone.settings.child","aj.field_guide_gui.bone.settings.child.interaction","aj.field_guide_gui.bone.settings.decendant","aj.field_guide_gui.bone.settings.decendant.interaction","aj.field_guide_gui.bone.settings.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.settings_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.settings_interaction","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.bone.settings.child","aj.global.bone.settings.child.interaction","aj.global.bone.settings.decendant","aj.global.bone.settings.decendant.interaction","aj.global.bone.settings.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.settings_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.settings_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/settings_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.settings_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.settings_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^0.9531 ^2.0625 ^-0.5 { Tags:["","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.bone.spell_wheel.child","aj.field_guide_gui.bone.spell_wheel.child.interaction","aj.field_guide_gui.bone.spell_wheel.decendant","aj.field_guide_gui.bone.spell_wheel.decendant.interaction","aj.field_guide_gui.bone.spell_wheel.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.spell_wheel_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.spell_wheel_interaction","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.bone.spell_wheel.child","aj.global.bone.spell_wheel.child.interaction","aj.global.bone.spell_wheel.decendant","aj.global.bone.spell_wheel.decendant.interaction","aj.global.bone.spell_wheel.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.spell_wheel_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.spell_wheel_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/spell_wheel_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.spell_wheel_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-0.0156 ^0.4844 ^-0.5 { Tags:["","aj.field_guide_gui.bone.challenges.child","aj.field_guide_gui.bone.challenges.child.interaction","aj.field_guide_gui.bone.challenges.decendant","aj.field_guide_gui.bone.challenges.decendant.interaction","aj.field_guide_gui.bone.challenges.tree","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.challenges_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.challenges_interaction","aj.global.bone.challenges.child","aj.global.bone.challenges.child.interaction","aj.global.bone.challenges.decendant","aj.global.bone.challenges.decendant.interaction","aj.global.bone.challenges.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.challenges_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.challenges_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/challenges_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.challenges_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.challenges_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-0.9844 ^0.3125 ^-0.5 { Tags:["","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.bone.quests.child","aj.field_guide_gui.bone.quests.child.interaction","aj.field_guide_gui.bone.quests.decendant","aj.field_guide_gui.bone.quests.decendant.interaction","aj.field_guide_gui.bone.quests.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.quests_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.quests_interaction","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.bone.quests.child","aj.global.bone.quests.child.interaction","aj.global.bone.quests.decendant","aj.global.bone.quests.decendant.interaction","aj.global.bone.quests.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.quests_interaction","aj.new"], response: false, width: 0.625f, height: 0.625f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.quests_interaction, tag=aj.new, distance=..3 ] run function aj:field_guide_gui/zzz/summon/as_interaction/quests_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.quests_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.quests_interaction.uuid set from storage animated_java:gu out
summon minecraft:interaction ^-0.0156 ^1.3125 ^-0.6875 { Tags:["","aj.field_guide_gui.bone.exit.child","aj.field_guide_gui.bone.exit.child.interaction","aj.field_guide_gui.bone.exit.decendant","aj.field_guide_gui.bone.exit.decendant.interaction","aj.field_guide_gui.bone.exit.tree","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.exit_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.exit_interaction","aj.global.bone.exit.child","aj.global.bone.exit.child.interaction","aj.global.bone.exit.decendant","aj.global.bone.exit.decendant.interaction","aj.global.bone.exit.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.exit_interaction","aj.new"], response: false, width: 0.5f, height: 0.453125f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.exit_interaction, tag=aj.new, distance=..2 ] run function aj:field_guide_gui/zzz/summon/as_interaction/exit_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.exit_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.exit_interaction.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.talents] run function aj:field_guide_gui/zzz/summon/as_node/talents
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.talents set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.gear] run function aj:field_guide_gui/zzz/summon/as_node/gear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.gear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.collection] run function aj:field_guide_gui/zzz/summon/as_node/collection
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.collection set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.settings] run function aj:field_guide_gui/zzz/summon/as_node/settings
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.settings set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.spell_wheel] run function aj:field_guide_gui/zzz/summon/as_node/spell_wheel
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.fill] run function aj:field_guide_gui/zzz/summon/as_node/fill
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.fill set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.border] run function aj:field_guide_gui/zzz/summon/as_node/border
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.border set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.number] run function aj:field_guide_gui/zzz/summon/as_node/number
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.number set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.challenges] run function aj:field_guide_gui/zzz/summon/as_node/challenges
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.challenges set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.quests] run function aj:field_guide_gui/zzz/summon/as_node/quests
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.quests set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.exit] run function aj:field_guide_gui/zzz/summon/as_node/exit
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.exit set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:field_guide_gui/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:field_guide_gui/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:field_guide_gui/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:field_guide_gui/zzz/summon/zzz/0 with storage animated_java:temp entry.data.interactions
execute on passengers if entity @s[tag=aj.field_guide_gui.node.fill] run function aj:field_guide_gui/zzz/summon/on_summon/bone_fill
execute on passengers if entity @s[tag=aj.field_guide_gui.node.number] run function aj:field_guide_gui/zzz/summon/on_summon/bone_number
execute at @s run function aj:field_guide_gui/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new