# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:field_guide_gui"
data modify storage animated_java:temp entry.data.rig_hash set value "83e24e905da7b461530ff5ebbd06d053434f3ec80692c60e69d1392bf0424d56"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^1.375 ^0.3125 { Tags:["","aj.field_guide_gui.bone.close.child","aj.field_guide_gui.bone.close.child.interaction","aj.field_guide_gui.bone.close.decendant","aj.field_guide_gui.bone.close.decendant.interaction","aj.field_guide_gui.bone.close.tree","aj.field_guide_gui.bone.main.decendant","aj.field_guide_gui.bone.main.decendant.interaction","aj.field_guide_gui.bone.main.tree","aj.field_guide_gui.entity","aj.field_guide_gui.interaction","aj.field_guide_gui.interaction.close_interaction","aj.field_guide_gui.node","aj.field_guide_gui.node.close_interaction","aj.global.bone.close.child","aj.global.bone.close.child.interaction","aj.global.bone.close.decendant","aj.global.bone.close.decendant.interaction","aj.global.bone.close.tree","aj.global.bone.main.decendant","aj.global.bone.main.decendant.interaction","aj.global.bone.main.tree","aj.global.entity","aj.global.interaction","aj.global.node","aj.global.node.close_interaction","aj.new"], response: false, width: 0.75f, height: 0.3125f, }
execute as @n[ type=minecraft:interaction, tag=aj.field_guide_gui.interaction.close_interaction, tag=aj.new, distance=..2 ] run function aj:field_guide_gui/zzz/summon/as_interaction/close_interaction
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.close_interaction set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.interactions.close_interaction.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.talents] run function aj:field_guide_gui/zzz/summon/as_node/talents
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.talents set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.gear] run function aj:field_guide_gui/zzz/summon/as_node/gear
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.gear set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.collection] run function aj:field_guide_gui/zzz/summon/as_node/collection
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.collection set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.settings] run function aj:field_guide_gui/zzz/summon/as_node/settings
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.settings set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.spell_wheel] run function aj:field_guide_gui/zzz/summon/as_node/spell_wheel
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.spell_wheel set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.fill] run function aj:field_guide_gui/zzz/summon/as_node/fill
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.fill set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.border] run function aj:field_guide_gui/zzz/summon/as_node/border
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.border set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.number] run function aj:field_guide_gui/zzz/summon/as_node/number
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.number set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.missions] run function aj:field_guide_gui/zzz/summon/as_node/missions
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.missions set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.quests] run function aj:field_guide_gui/zzz/summon/as_node/quests
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.quests set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.field_guide_gui.node.close] run function aj:field_guide_gui/zzz/summon/as_node/close
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.close set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:field_guide_gui/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:field_guide_gui/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:field_guide_gui/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:field_guide_gui/zzz/summon/zzz/0 with storage animated_java:temp entry.data.interactions
execute on passengers if entity @s[tag=aj.field_guide_gui.node.fill] run function aj:field_guide_gui/zzz/summon/on_summon/bone_fill
execute on passengers if entity @s[tag=aj.field_guide_gui.node.number] run function aj:field_guide_gui/zzz/summon/on_summon/bone_number
execute at @s run function aj:field_guide_gui/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new